MODULE_NAME=test
KERNEL_PATH ?= /lib/modules/$(shell uname -r)/build
$(MODULE_NAME)-objs := hook.o setpage.o symbol.o
KERNEL_PATH=/opt/linux/linux/
ARCH=arm64
CROSS_COMPILE=aarch64-linux-gnu-
obj-m := $(MODULE_NAME).o

all:
	make -C $(KERNEL_PATH) M=$(PWD) modules ARCH=$(ARCH) CROSS_COMPILE=$(CROSS_COMPILE)

clean:
	make -C $(KERNEL_PATH) M=$(PWD) clean
